name: petconect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' # VersiÃ³n actualizada para mejor compatibilidad

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1 # Opcional, para guardar directamente en el dispositivo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true